name: PlatformIO CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core and esptool
        run: pip install --upgrade platformio esptool

      - name: Build PlatformIO Project LILYGO-T-Dongle-S3 
        run: pio run --environment LILYGO-T-Dongle-S3 --target create_image

      - name: Upload LILYGO-T-Dongle-S3 artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LILYGO-T-Dongle-S3 Firmware image.bin
          path: image.bin

      - name: Build PlatformIO Project Waveshare-ESP32-S3-LCD-1_47
        run: pio run --environment Waveshare-ESP32-S3-LCD-1_47 --target create_image
            
      - name: Upload Waveshare-ESP32-S3-LCD-1_47 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waveshare-ESP32-S3-LCD-1_47 Firmware image.bin
          path: image.bin

      - name: Build PlatformIO Project Generic-ESP32-S2
        run: pio run --environment Generic-ESP32-S2 --target create_image
          
      - name: Upload Generic-ESP32-S2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generic-ESP32-S2 Firmware image.bin
          path: image.bin

      - name: Build PlatformIO Project Waveshare-RP2040-GEEK
        run: pio run --environment Waveshare-RP2040-GEEK
            
      - name: Upload Waveshare-RP2040-GEEK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Waveshare-RP2040-GEEK Firmware binaries
          path: .pio/build/Waveshare-RP2040-GEEK/*.bin

      - name: Build PlatformIO Project M5-Atom-S3U
        run: pio run --environment M5-Atom-S3U --target create_image
              
      - name: Upload M5-Atom-S3U artifact
        uses: actions/upload-artifact@v4
        with:
          name: M5-Atom-S3U Firmware image.bin
          path: image.bin